### ISSUE TITLE
Docker in Galaxy in Docker

### ISSUE THREAD

**Issue by mhabsaoui** [lappsgrid-incubator/galaxy-appliance#5]
Hi,

I opened this topic about the possibility to run jobs in separate Docker containers : 

e.g. Galaxy is in a Docker container (docker-galaxy-stable) with the Docker activated (jobs_conf.xml  <destination id="docker_local" runner="local">). We want to run an NLP tool that is found in a Docker image (existing on Host machine).

Outside docker, it works like hell, but inside Docker it becomes a bit complex : 
https://github.com/andrewcstewart/galaxy-docker

https://github.com/bgruening/docker-galaxy-stable/blob/d37827cb038d43840addfaaca79ad40f428b7485/galaxy/cgroupfs_mount.sh

How dow deal with this ?

thanks.

**Comment by ksuderman** [comment]
We have not tried running any *Docker in Docker* tools yet.

> Outside docker, it works like hell, but inside Docker it becomes a bit complex :

Do you have your Dockerized NLP tool working in Galaxy with the Docker activated job_conf.xml file?

**Comment by mhabsaoui** [comment]
> Do you have your Dockerized NLP tool working in Galaxy with the Docker activated job_conf.xml file?

Yep, with Galaxy not dockerized and the Docker option activated in job_conf.xml file => the Dockerized NLP tool (as image on Host) is reachable and works.

Now we want to do the same, except Galaxy is dockerized too ;)

Thanks.

**Comment by ksuderman** [comment]
You may want to ask on the Galaxy mailing list as this is more of a Galaxy issue.  You may also want to try using a more recent Galaxy Docker image.  We are still using 16.04 for our Galaxy appliances.

**Comment by mhabsaoui** [comment]
Right. Thanks

**Comment by ksuderman** [comment]
Let me know how you make out. I just don't have any Dockerized tools to test with at the moment.
